### ISSUE TITLE
"Sort by" and "ordering" commands in web UI

### ISSUE THREAD

**Issue by MidnightLightning** [Hoxly/asksteem-docs#2]
The front-end web UI at https://www.asksteem.com allows for advanced searching like using the `tags:` modifier, but it doesn't seem to honor the `sort_by` nor `order` properties that the search API uses. Sorting search results in the front-end UI would be very useful!

**Comment by KylePiira** [comment]
Hi there,
You are correct that `sort_by` and `order` are not currently supported on the web UI. I will see if I can add that functionality later this week.
